pipeline {
    agent any

    tools {
        maven 'M3'
    }

    environment {
        SONAR_SERVER = 'SonarQube'
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out source code from Git repository...'
            }
        }

        stage('Build & Test') {
            steps {
                echo 'Compiling source code and executing unit tests...'
                dir('Telemetry_Guardian') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo 'Injecting SonarQube environment and initializing SAST scanning...'
                dir('Telemetry_Guardian') {
                    withSonarQubeEnv("${SONAR_SERVER}") {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Enforce Quality Gate') {
            steps {
                echo 'Enforcing architectural thresholds and waiting for Quality Gate status...'
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Secure Container Image') {
            steps {
                echo 'Quality Gate passed! Building rootless multi-stage production Docker image...'
                dir('Telemetry_Guardian') {
                    sh 'docker build -t telemetry-guardian:latest .'
                }
            }
        }
    }

    post {
        success {
            echo '=================================================='
            echo ' SUCCESS: Entire CI/CD Pipeline Executed Smoothly!'
            echo '=================================================='
        }
        failure {
            echo '=================================================='
            echo ' FAILURE: Pipeline stopped due to an error or Quality Gate breach.'
            echo '=================================================='
        }
    }
}